prod:
  catalog_name: mlops_prod
  schema_name: credit_risk
test:
  catalog_name: mlops_test
  schema_name: credit_risk
dev:
  catalog_name: mlops_dev
  schema_name: credit_risk

primary_keys:
  - CustomerId


experiment_name_basic: /Shared/credit-risk-basic
experiment_name_custom: /Shared/credit-risk-custom

learning_parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

target: Risk
