prod:
  catalog_name: mlops_prod
  schema_name: credit_risk
test:
  catalog_name: mlops_test
  schema_name: credit_risk
dev:
  catalog_name: mlops_dev
  schema_name: credit_risk

primary_keys:
  - CustomerId


experiment_name_model: /Shared/credit-risk-basic
experiment_name_pyfunc_model: /Shared/credit-risk-custom

hyperparameters:
  learning_rate: 0.01
  n_estimators: 100

target: Risk
numerical_features:
  - Credit_amount
  - Duration
  - Age
categorical_features:
  - Sex
  - Job
  - Housing
  - Purpose
  - Saving_accounts_ordinal_enc
  - Checking_account_ordinal_enc
